Repository tungnv2k/student_utils, pull requests merged in 2020-04, with the labels that each got.

#24 Refactor #20 merge request
  lib/screens/calendar_screen.dart
  lib/screens/login_success_screen.dart
  lib/screens/note_list_screen.dart
  lib/screens/note_screen.dart
Labels: refactor

#26 [Note-taking] Fix dispose() was called on null
  lib/screens/note_screen.dart
Labels: bug, refactor

#30 [Calendar] Reorder list events
  lib/service/calendar/google_calendar_service.dart
Labels: invalid

#31 [Calendar] Fix Invalid credentials when switching view
  lib/screens/login_success_screen.dart
  lib/service/calendar/google_calendar_service.dart
  lib/service/googleapi/apis.dart
Labels: bug

#33 Hotfix #32: Add back button to pop back from note screen
  lib/components/app_bar.dart
  lib/screens/note_screen.dart
Labels: bug

#34 Hotfix #29: Fix Invalid Credentials
  lib/screens/login_success_screen.dart
  lib/service/calendar/google_calendar_service.dart
Labels: bug

#40 [Calendar] Table calendar
  lib/screens/calendar_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#45 [Calendar] Add ScrollablePositionedList
  lib/screens/calendar_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#47 [Refactor] Fix bug and refactor view
  lib/components/app_bar.dart
  lib/main.dart
  lib/screens/calendar_screen.dart
  lib/screens/login_screen.dart
  lib/screens/login_success_screen.dart
  lib/screens/no_login_screen.dart
  lib/service/googleapi/apis.dart
  lib/service/login/sign_in.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#66 Improve bookmark, note and calendar data storage
  lib/app_life_cycle.dart
  lib/screens/calendar_screen.dart
  lib/screens/login_screen.dart
  lib/screens/login_success_screen.dart
  lib/screens/no_login_screen.dart
  lib/service/file/bookmark/bookmark_file.dart
  lib/service/file/note/note_file.dart
  lib/service/login/sign_in.dart
  lib/storage/bookmark_storage.dart
  lib/storage/calendar_storage.dart
  lib/storage/note_storage.dart
Labels: enhancement

#67 [Login] App onResume NPE hotfix
  lib/screens/login_success_screen.dart
Labels: bug

#68 [Bookmark] Link shareable to app
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/se/su/app/student_utils_app/MainActivity.java
  lib/screens/login_success_screen.dart
Labels: enhancement

#69 [Test] Add test dependencies
  .gitignore
  pubspec.yaml
Labels: enhancement

#70 [Test] Add test sign in with google
  test/sign_in_test.dart
Labels: enhancement

#71 [API] Update api method
  lib/service/googleapi/apis.dart
  pubspec.lock
Labels: refactor

#72 [Test] Unit test for events and read file
  test/get_events_test.dart
  test/read_file_test.dart
Labels: enhancement
